# -*- coding: utf-8 -*-
"""Access_Modifiers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vh9oFtMzNkOaA_64nDE0TfRTPXcIKfp6
"""

class Employee:
  def __init__(self,age,name):
    self.age = age     #public variable
    self.name = name    #public variable

obj = Employee(21,"Ram")
print(f"The name of Employee is: {obj.name}")

class Employee:
  def __init__(self):
    self.age = 21
a = Employee()
print(a.age)

class Employee:
  def __init__(self):
    self.__age = 21 #Private
a = Employee()
#print(a.__age)
print(a._Employee__age)

class Student:
  def __init__(self):
    self._name = "harry"
a = Student()
print(a._name)

