# -*- coding: utf-8 -*-
"""Alternative_Constructors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1URJzzcUXa-wr0GqDpBQfBf6SUPr0LSvJ
"""

class Employee:
  def __init__(self,name,salary):
    self.name = name
    self.salary = salary
  @classmethod
  def fromStr1(cls,string):
      return cls(string1.split("-")[0],int(string1.split("-")[1]))

  @classmethod
  def fromStr2(cls,string2):
      return cls(string2.split("%")[0],int(string2.split("%")[1]))
  @classmethod
  def fromStr3(cls,string3):
      return cls(string3.split("__")[0],int(string3.split("__")[1]))

e1 = Employee("Harry",12000)
print(e1.name,e1.salary)

string1 = "John-1200"
e2 = Employee.fromStr1(string1)
print(e2.name ,e2.salary)

string2 = "Meghan%1298"
e2 = Employee.fromStr2(string2)
print(e2.name ,e2.salary)

string3 = "Taylor__1100"
e3 = Employee.fromStr3(string3)
print(e3.name ,e3.salary)

# e2 = Employee(string.split("-")[0],string.split("-")[1])
# print(e2.name,e2.salary)

