# -*- coding: utf-8 -*-
"""Break&Continue.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AvN0DlNA3B-__WgqHhOt4yA-XJntb6-l
"""

#Break statement:Enables to skip over a part of the code.
for i in range(12):
  if(i==10): #Exit loop at this condition
   break
  print("5 X",i+1,"=",5 *(i+1) )

print("Exiting loop")

#Continue Statement:Skips the rest of the loop statements and causes the next iteration to occur.
for i in range(12):
  if(i==10):
    print("Skip the iteration")
    continue
  print("5 X",i+1,"=",5 *i )

for i in[2,3,4,6,8,0]:
  if(i%2!=0):
    continue
  print(i)