# -*- coding: utf-8 -*-
"""Class_Methods.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16jfzwoqaTN4WWBloC-6mLE7vNwkk4v79
"""

#class method is bound to class and not the instance of class
#Takes cls as Ist arg instead of self.

class Employee:
  company = "Apple"
  def show(self):
    print(f"The name is {self.name} and company is {self.company}")
  @classmethod
  def ChangeComp(cls,newComp):
    cls.company = newComp

e1 = Employee()
e1.name = "Harry"
e1.show()
e1.ChangeComp("Tesla")
e1.show()
print(Employee.company)

