# -*- coding: utf-8 -*-
"""Class_Intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P6YkJGjD6ZIIvg3ObUwF8xaXgHZd4PXf
"""

class Person:
  name = "Harry"
  age  = 25
  Residence = "UP"
a = Person()
print(a.name,a.age)

class Person:
  name = "Harry"
  age  = 25
  Residence = "UP"
  def info(self):
   print(f"{self.name} is {self.age}.") #self refers to the current instance of class
a = Person()
a.name = "Tom"
a.age  = 25
b = Person()
b.name = "Nikhil"
b.age  = 35
#print(a.name,a.age)
a.info()
b.info()

