# -*- coding: utf-8 -*-
"""Constructors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P7bSH7bauRd_IXLNbIu6mqw6qZEtihZr
"""

class Person:
  name = "Tom"
  age = "25"

  def info(self):
    print(f"{self.name} is {self.age}")
a = Person()
a.info()

class Person:
  def __init__(self):
    print("Hey hello!")

a= Person()
b = Person()

##Constructor is a special method in class to create&initialize an obj of class>
##Default Const and Parameterized Const
class Person:
  def __init__(self,n,a):
   self.name = n
   self.age  = a
  def info(self):
   print(f"{self.name} is {self.age}")
a= Person("Harry", 25)
b = Person("Zara", 18)
a.info()
b.info()

class Info:
  def __init__(self,y,z):
    self.animal = y
    self.group =  z
  def dets(self):
   print(f"{self.animal} is {self.group}")

a = Info("Tiger", "Mammal")
a.dets()

class Info:
  def __init__(self,animal,group):
    self.animal = animal
    self.group =  group
  def dets(self):
   print(f"{self.animal} belongs to {self.group}")
obj1 = Info("Crab","Sea animal")
obj2 = Info("Lion","Wild animals")
print(obj1.animal, "belongs to the ", obj1.group, "group.")
obj1.dets()
obj2.dets()

