# -*- coding: utf-8 -*-
"""Day1Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZK1aAMmkXC5l70QCBreVismz86Ve0uFN
"""

print("hello")
print("hey")
print(10*8)

##Variable:define for storing a particular data type

abcd = "Kashmir"

print(abcd)



#variable name cannot start with a number
1abc = "India"

abcd1 = "anything"

print(abcd1)

def="anything"

fromm = "abcd"

print("hellooooo")