# -*- coding: utf-8 -*-
"""Day2Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GR86Efp7l6r_szb8dWmPpHV83GZvy1uv
"""

print(The product is :- 10*3)

#Comments:Helper text without effecting program

# Line 1comment
# Line 2 comment
# LIne 3 comment
# print("I am learning comments")
print("Test")

"""hello
hello
hello"""
#Multi Line Comments using triple quotes
print ("Test")

#Python is a case sensitive language
 cat = "z"

#Data Type:Type of data being used
var1  = "Dog"
x = "cat"

#Data types:
integer: -10....10
float:10.3,2.4,
string:"cat","dog"
boolean:true,false"""

type(x) #using type function to infer the type of data type being used

y = False
print (type(y))

type(3.45)

# Type Casting:converting one data type into another
x = 2.7
type (x)

x = int(x)
print(x)
print (type(x))

y = 5+5
print(y)
type(y)

y = str(5) + 5
print(y)
type(y)

a = '2'
b = 2
print(a)
print(type(a))
print(type(b))