# -*- coding: utf-8 -*-
"""Day3Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VQ7n24OQlu_fvwA4JsMQDZl-uL1IF_6g
"""

##DATA TYPES:
var = True
print (var)

print (type(var))

var2 = False
print (var2)

var3 =  'False'
print(var3)
print(type(var3))

## String
xyz = "This is a string"
print(xyz)
print(type(xyz))

x = This is a string

x = True

a1 = False
a2 = "False"

print(a1)
print(a2)
print(type(a1))
print(type(a2))

if a1:
  print("This condition is triggered using a1 ")

if a2:
  print("This condition is triggered using a2 ")

#LIST:Used to store multiple data types using square brackets and separating the items using comma.
myFirstList = []
print(myFirstList)

print(type(myFirstList))

list2=[1,2,2,3,4,5,6,7,8,9,3,1,0]

print(list2)

list3=['apple',2.567,'Alpha',98,True]

print(list3)

print(type(list3))

ListwithoutCommas=[1@1@3]  ##Can separate elements in list only using ","

len(myFirstList) #Have to use a list variable  to find it's length.

len(a1)
