# -*- coding: utf-8 -*-
"""Day4Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KEBxZtndXz1BDzuBOYXRHwIXEtxhw7E9
"""

classMarksEnglish=[18,19,17,20,12,13]    # 0 based indexing in Python
print(classMarksEnglish[4])

#Changing elements in a list
classMarksEnglish=[18,19,17,20,12,13]
classMarksEnglish[5]=20
print(classMarksEnglish)
print(classMarksEnglish[5])

#Range of values:
print(classMarksEnglish[2:5])

# Appending the elements
classMarksEnglish.append(10)
print(classMarksEnglish)

#Inserting element at a specific index:
classMarksEnglish.insert(1, 15)
print(classMarksEnglish)

#Removing an element:
classMarksEnglish=[18,19,17,20,20,13]
classMarksEnglish.remove(20)
print(classMarksEnglish)

classMarksEnglish=[18,19,17,20,20,13]

classMarksEnglish.pop(2)

classMarksEnglish.pop() #When not mentioned,removes last element by default.

print(classMarksEnglish)

classMarksEnglish.clear()  #erases all elements within the list.
print(classMarksEnglish)

newList = [19,2,21,3,5,-9]

print(newList)

newList.sort()
print(newList)

newList.sort(reverse=True)
print(newList)

