# -*- coding: utf-8 -*-
"""Day5Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_4sgC2BLWvOT9-ud4RLYGA9LGh3OK5CR
"""

num = int (input("Please enter  a  number :"))

print(num)

print(type(num))

#INDENTATION IS HOW MANY TABS ARE THERE FROM START TO END LINE OF CODE
print("Abc")

print("xyz")
  print("Ab")

#Conditions in Python:
num = 10
if num > 3 :
  print("Hello")
  print("paris")
  print (int(num) *10)

if 10>5:
  print("This condition is true")
  print("This is the second line")

#Comparison Operrators:
#EQUAL TO COMPARISON IS DONE USING "=="
a = 10
if a ==10:
  print("A is equal to 10")

#cHeck if a value isn't equal to another value
if a != 12:
  print("A is not equal to 10")

# == , > ,< , !=, >=,<=
if a <= 5:
  print("A is not equal to 5")

##Assignment operator:
x = 12

x +=1
print(x)

x-=1

print(x)

x = 12
x/=6
print(x)

# Commented out IPython magic to ensure Python compatibility.
#Arithematic Op:
+ : Additipn
- : Subtraction
/ : Division
# % : Modulus
** : Exponentional

num1= 1
num2 =2

print(num1+num2)

print(num1-num2)

num3  = 19
num4  = 4

print(num3 % num4)

x = 2
y = 3
print(x**y)

q = (1+2)*3
print(q)   #Operator gets evaluated as per their precedence

r = 14-4+(3+2)
print(r)

#If else:
num10 = 3
if num10 > 16:
  print("It is greater than 16")
else:
  print("It is less than 16")

#If ,else if,else
if num10 >12:
   print("It is greater than 16")
elif num10 >10:
  print("It is greater than 10 but less or equal to 16")
else:
  print("It is less than or equal to 10")

else:
  print("HaloGlow")

if 10>5:
  print("This is valid if condition")