# -*- coding: utf-8 -*-
"""Day7python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WQ-PCRnPUv0bbLsd5EPoETKhGN8-Tf7P
"""

#Creating a list:
elements  = [1,4 ,7,9,6]

elements.sort()
print(elements)

elements.insert(1,20)
print(elements)

elements.pop(3)

print(elements)

elements.sort(reverse=True)
print(elements)

print(elements)

elements.clear()
print(elements)