# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kr9tMGFLOrEXLf7-7jquDjKvDWr9lT7B
"""

#Dictionary:stores the element using key-value pair where keys are used to access values in dictionary

classmates ={'Tony':' drives fast' , 'Emma':' reads slowly' , 'Lucy':' sits behind me'}

print(classmates)

print(classmates['Emma'])

print(classmates['Lucy'])

for k,v in classmates.items():

  print(k+v)

