# -*- coding: utf-8 -*-
"""Do while Loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SsuMp6yxx9u98f75XFbVA5puiNu0e71f
"""

#Do while:
i =0
while True:
  print(i)
  if (i%100==0):
    break

while True:
  num =int(input("Enter a number: "))
  print(num)
  if not num > 6:
    break