# -*- coding: utf-8 -*-
"""Enumerate Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tXGOBVKsymg0qJfoswTMKF8CAc2hmKa
"""

#Enumerate FUnc:
marks =[10,12,14,15,17,6]
index = 0
for mark in marks:
  print(mark)
  if(index==3):
   print("Yaayy!!")
  index+=1

marks =[10,12,14,15,17,6]
for index,mark in enumerate(marks):
  print(mark)
  if(index==3):
   print("Yaaay!!")

marks =[10,12,14,15,17,6]
for index,mark in enumerate(marks):
  print(index,mark)

fruits= ['apple','cherry','fig','pineapple']
for index,fruit in enumerate(fruits):
 print(index,fruit)

random= ['apple','cherry','fig','pineapple',True,12.4,7]
for index,random in enumerate(randoms):
 print(index,random)

#Changing the start index:
fruits= ['apple','cherry','fig','pineapple']
for index,fruit in enumerate(fruits,start=1):
 print(index,fruit)