# -*- coding: utf-8 -*-
"""Euclidean distance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_vtPDyeaWSM4W093OMhqVKvLufSKRgh9
"""

#Program to calculate Euclidean Distance:

def distance(x1,y1,x2,y2):
  d = ((x2-x1)**2 + (y2-y1)**2)**0.5
  print("The distance between the points is:")
  return d
distance(1,2,3,4)