# -*- coding: utf-8 -*-
"""Even Numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pi0byPuNC0FV_00buoRohesED6kCZDIx
"""

# Printing Even numbers:-
# Using a for loop
print("Even numbers from 0 to 12 using for loop:")
for i in range(0, 13, 2):
    print(i)

# Using a while loop
print("Even numbers from 0 to 50 using while loop:")
num = 0
while num <= 50:
    print(num)
    num += 2

