# -*- coding: utf-8 -*-
"""Exception Handling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UBqHQHh-5M4mybcIMH8814MaZYPgqnqM
"""

#Exception Handling:
x = 4
y = "Hello"
z = x+y
print(z)

x = 4
y = "Hello"
try:
 z = x+y
except:
  print("Can't add an int & str")

x = 4
y = "Hello"
try:
 z = x+y
except TypeError:
  print("Error:cannot add an int and a str")

