# -*- coding: utf-8 -*-
"""Exercise_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D2F5mbZSM0wizeo4znVGrjy2nMPDFIfZ
"""

!pip install pytz

from datetime import datetime
import pytz
import time

time_zone = pytz.timezone('Asia/Kolkata')
current_time = datetime.now(time_zone)
hour = datetime.now(time_zone).hour

print("Details of your Time-Zone:", current_time.strftime("%d-%m-%Y    %H:%M"))

time.sleep(2)  # Introduces a slight delay before displaying the greeting for a smooth experience.

if 4 <= hour < 12:
  print('''Each morning we are born again. What we do today is what matters most.
Have a wonderful day ahead!''')

elif 12 >= hour <16:
  print("Good Afternoon!")
  time.sleep(2)
  print("Afternoons are the pause between morning’s hustle and evening’s calm —a time to reflect, recharge, and smile.")

elif 16 > hour <=19:
  print("Good Evening!")
  time.sleep(2)
  print("As the evening sky fades into night, may your heart be filled with peace and your mind with gratitude.")

else:
  print('''A good laugh and a long sleep are the best cures in the doctor’s book.
  Good Night!''')

