# -*- coding: utf-8 -*-
"""Exercise_5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jstAu-nNqH0ln6mh-fD36WSj0Wkfvsfm
"""

#Snake Water Gun Game:
import random

def check(Comp,Player):
    if Comp == Player:
     return 0
    if (Comp == 0 and Player == 1):
     return -1
    if (Comp == 1 and Player == 2):
     return -1
    if (Comp == 2 and Player == 0):
     return -1
    return 1
while True:
    Comp = random.randint(0, 2)
    Player = int(input("Enter 0 for Snake, 1 for Water & 2 for Gun: \n"))
    if Player > 2:
        print("Input should be less than or equal to 2. Exiting...")
        break
    score = check(Comp,Player)
    print("Player_Choice: ",Player)
    print("Computer_Choice: ",Comp)
    if(score == 0):
      print("It\'s a Draw.Try again.")
    elif(score == -1):
      print("You lose!!")
    else:
      print("Yaaay!!You won")
    break

