# -*- coding: utf-8 -*-
"""Exercise_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19liad2GgycAfyMe7y-7cNcHceMi0VRG8

**Building a calculator:**
"""

a = int(input("Enter the first number: "))
b = int(input("Enter the second number: "))
c = input("Enter the operator: ")

if c == "+" :
    print("The sum of a and b is\n", a+b)
elif c == "-" :
    print("The difference of a and b is\n", a - b)
elif c == "*" :
    print("The product of a and b is\n", a * b)
elif c == "/" :
    print("The division of a by b is\n", a / b)
elif c == "%" :
    print("The remainder of a divided by b is\n", a % b)
else:
    print("Invalid operator")