# -*- coding: utf-8 -*-
"""Exercise_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sR5rMqpucZ2AK8-BWHgCrhjE0cHQA-3P
"""

import time
t = time.strftime('%H:%M')
print(t)
hour = int(time.strftime('%H'))
print(hour)

if(hour>0 and hour<12):
  print("Good Morning")
elif(hour==12 or hour<=14):
  print("Good Afternoon")
else:
  print("Good evening")

#Program to print current time to the user and greet him accordinly:
from datetime import datetime
import pytz

zones = pytz.all_timezones
#print(zones)
#Output: all timezones of the world.
from datetime import datetime
import pytz

IndiaTz = pytz.timezone("Asia/Calcutta")
timeInIndia = datetime.now(IndiaTz)
currentTimeInIndia = timeInIndia.strftime("%H:%M:%S")
print("The current time in India is:", currentTimeInIndia)
hour = int(timeInIndia.strftime('%H'))
print(hour)

if(hour>0 and hour<12):
  print("Good Morning!")
elif(hour==12 and hour<=14):
  print("Good Afternoon!")
else:
  print("Good evening!")