# -*- coding: utf-8 -*-
"""For Loop Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DPUfFY-tiaNRWGFwBUD4vc-fqhql2dui
"""

fruits = ["apple", "banana", "cherry"]
for x in fruits:
  print(x)

fruits = ["apple", "banana", "cherry"]
print(fruits)

for x in "banana":
  print(x,end=",")

Country = ["India", "Pakistan", "Bhutan"]
Capitals = ["New Delhi", "Islamabad", "Thimpu"]

for x in Country:
  print(x.upper())
  for y in Capitals:
    print(y.lower())

n = 6
for i in range(0,n):
  print(i)