# -*- coding: utf-8 -*-
"""Function Arguments.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m7m5WtHEKPAd_VwuNQlHTbAQtRU8CRAB
"""

#Function Arguments:
##Default Arg
#Keyword Arg
##variable Leng Arg
##Required Leng Arg

def average(a=9,b=1):
  print("The avg is", (a+b)/2)
#average(4,6)
#average(1,4)
average(3)
#average(b=9)

#Keyword Arg:
def average(a=9,b=1):
  print("The avg is", (a+b)/2)

average(b=9,a=21)

#Reqd Arg:
def average(a,b,c=1):
  print("The avg is", (a+b+c)/2)

average(5,6)

def average(*numbers):
  print(type(numbers))
  sum=0
  for i in numbers:
    sum =sum+i
  print("Avg is: ",sum/len(numbers))

average(5,6,4,3,10,18)

