# -*- coding: utf-8 -*-
"""Global&LocalVariable.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LvSYtEm4yv2O2Kmn0H1XO1xmT8jckmi4
"""

x = 11 #global variable

def learn_func():
  global x
  x = 6
  y = 4
  print(x+y)
  print(x)
  print(y) #local variable
learn_func()
print(x+6)
##print(y) will throw an error as we can't access a local variable outside a func