# -*- coding: utf-8 -*-
"""Import_Statement.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tIQIClz_ySfpCU12Xc2qyn5t0GqmURUX
"""

import math
result = math.sqrt(9)
print(result)

from math import sqrt
result = sqrt(9)
print(result)

from math import sqrt as s
result = s(9)
print(result)

from math import *
print(pi)

import math as m
result = m.sqrt(9)
print(result)

import math
print(dir(math))
print(type(math.e))