# -*- coding: utf-8 -*-
"""Operators.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVIkxsh2IjzsV2gUPSVlXbno99TFauPW
"""

#Operators:
#Arithematic Operators:
print("3+2 is:",3+2)
print("3-2 is:",3-2)
print("3*2 is:",3*2)
print("3**2 is:",3**2) #Exponential operator
print("3/2 is:",3/2)
print("3//2 is:",3//2) #Floor divison op,gives only the integer value and not the decimal behind it.
print("3%2 is :",3%2)  #MOd op gives remainder

#Assignment Op:Assigns value
x = 5
print(x)

x+=10 #Adds the value 10 to initial value in x
print(x)

x/=5
print(x)

x-=2
print(x)

#Comparion Op:
i = 5
print(i != 6)

print( i > 6)

print(i < 8)

print(i == 5)

print(i <=5)

print(i >=5)

#Logical OP: And,OR,NOT
#And indicates both should be true to give true and OR indicates either of one should be true to give true
i = 5
print(6 and i) #Check

a = True
b = False
print( a and b)
print(b and b)
print(a or b)
print( b or b)
print(a or a)

#Identity OP:is and is not
a = True
b = False

x = 5
y = 7

print( a is a)
print( a is b)
print(a is not b)
print(x is not y)

print( 5 is not 7)

#Membership Op:in ,not in
list =[3,2,31,4,5,8,5,89,76]
print(list)
print(5 in list)
print(11 in list)
print(11 not in list)
list_name =["Sadaf","Qurat","Suzain"]
print(list_name)
print("Suzzain" in list_name)

#Bitwise operators:
"""0 - 00
1 - 01
2 - 10
3 - 11"""

print(0 | 1)
print(2 & 3)

#Basic Program to implement comparison operators on integers
num1 = 1000
num2 = 105
if num1 > num2:
  print("True.")
elif num1 < num2:
  print("False.")
else:
  print("Both are equal.")