# -*- coding: utf-8 -*-
"""Operators Practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CVZR3TWiw1kO0T9Llpken2MD_pMEXycR
"""

#Basic Program to implement comparison operators on integers
num1 = 1000
num2 = 105

if num1 > num2:
  print("True.")
elif num1 < num2:
  print("False.")
else:
  print("Both are equal.")

#Program using logical operators:
x = 10 + 20 *6
print(x)

name = "Fred"
age =  10

if name == "Fred" or name == "John" and age >=5:
  print("Hello,I am Fred!")
else:
  print("Wrong identity")