# -*- coding: utf-8 -*-
"""Palindrome.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qivJZA7Nnp8KqfSZxgrL9XCCyNVXsSy6
"""

#Program to check if a string is pallindrome:
def is_palindrome(x):
  a1 = x
  b1 = x[::-1]

  return a1 == b1
is_pallindrome(input("Enter a string:"))

def is_Palindrome(x):
  a = x
  b = x[::-1]
  return a==b
is_Palindrome("hello")