# -*- coding: utf-8 -*-
"""Tuples.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11QYhVM1guZ2InPyLwRkDQKT8ZlZlMIDI
"""

tup = (9,8,7,5,6) #Even if you have only one element in a tuple separate it with a comma,else it will be considered as an integer.

#tup[0] = 8  Doesn't support item assignment.
#tup1.append("Anna")

print(type(tup),tup)

tup1 = (12,6.4,True,'Albert')
tup2 =('Elf','Elsa','Olaf')

print(tup1)
print(tup2)
print(tup1[0])
print(tup1[1])
print(tup1[2])
print(tup1[3])
print(tup1[-2])
print(len(tup1))
#print(tup1[15])  Index out of range
if True in tup1:
  print("Yes it is in the tuple")
print(tup1[1:4])

#Changing Tuples:
countries = ("Spain","Italy","Germany","Norway","Berlin")

temp = list(countries)
temp.append("Russia") #adding an element
temp.pop(1) #removing an element
temp[2]="Finland" #changing an element
countries =tuple(temp)
print(countries)

country = ("Pakistan" , "India", "Bangladesh", "Bhutan")
capitals = ("Islamabad","Delhi","Dhaka","Thimpu")
country_capitals = country +  capitals ###CHECK IF YOU INSERT \N IN BETWEEN
res =[(value(country),value2(capitals)) for value in country and value1 in capitals]
print(res)
#print(country_capitals)

tup1 =(1,5,31,34,3,7,8,3,0)
print(tup1.count(3))
print(tup1.index(1))
print(tup1.index(3,5,8))
print(len(tup1))

#Creating a list of tuples,element and it's cube:
list1 =[1,2,3,4]
res = [(value,pow(value,3)) for value in list1]
print( res)