# -*- coding: utf-8 -*-
"""PythonPractice24Jan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tKxxJTJc3XC-lBmRGUBROYSP8g7XGkrM
"""

print("   / |")
print("  /  |")
print(" /   |")
print("/____|")

print("       *")
print("      **")
print("     ***" )
print("    ****")
print("   *****")
print("  ******")

print("There once was a man named John,")
print("he was 35 years old.")
print("He really liked the name John,")
print("but didn't like being 35.")

#DOING THE ABOVE PROBLEM USING VARIABLES FOR NAME & AGE:-
char_name = "John"
char_age="35"
print("There once was a man named " + char_name )
print("he was " + char_age + " years old.")
print("He really liked the name, " + char_name )                                               #
print("but didn't like being "+ char_age +".")

char_name = "John"
char_age = "35"
print("There once was a man named " + char_name + " ,")
print("he was " + char_age + " years old.")

char_name = "Mike"
char_age = "70"
print("He really liked the name, " + char_name + "")
print("but didn't like being "+ char_age +".")

x = "There once was a man named John,"
y = "he was 35 years old."
z = "He really liked the name John,"
a = "but didn't like being 35."

print(x + "\n " + y)
print(len(y))
print( x + y + z + a)
print(z + a)

#STRINGS:-
phrase = "Giraffe Academy"
print(phrase.replace("Giraffe" ,"Rhino"))
print(phrase + " is cool.") #Concatenation of a String.
print(phrase.lower())#Used a function lower to change the letters to lower case.
print(phrase.upper())#Used a function upper to change the letters to upper case.
print(phrase.isupper())#Used to check if the string is in uppercase or not
print(phrase.upper().isupper())#Changes the string to uppercase and then prints true or false value.
print(len(phrase))#prints length of String.
print(phrase[14])#The first character starts from zero and this will give the position of character within the string
print(phrase.index("ff")) #Index Func tells us where that particular character is located within the string
print("Giraffe\nAcademy")
print("Giraffe \"Academy")
print("Giraffe \ Academy")

phrase1 = "Summer "
phrase2 = "is Sunny."
print(phrase1 + phrase2)
print(len(phrase1))
print(phrase1.replace ("Summer", "Winter"))
print(phrase1 + " is hot")
print(phrase1.upper())
print(phrase2.lower().isupper())
print(phrase1[4])
print(phrase2.index("nn"))
print("Global \ warming")