# -*- coding: utf-8 -*-
"""PythonPractice25Jan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sMfVDPh7nVy73w6qVaPneGktIJi43WKd
"""

print(2)

print(4.889)

print(-90)

print( 9 + 6)

print(9-15)

print(3*4+7)

print( (3+4)*2)

print(10 % 3)

print(15 % 5)

my_num =5
print(my_num)
print(my_num * 5)

my_num = 5
print(str(my_num) + ":My Fav Num")
print((my_num) + ":My Fav Num") #Can't add a string to an integer value

print(type(str(my_num)))

my_num = -5
print(abs(my_num)) #Gives absolute value of the number.

print(pow(3,10))   #Allows to pass 2 pieces of info,the number and the power you want to take that number to.

print(max(3,10,89)) #Gives max of numbers
print(min(3,10,89))

print(round(3.9)) #Gives roundoff of a num.
print(round(3.199))

from math import *  #Using math func to get access of many math functions.

print(floor(3.9)) #Graps the lowest number eliminating the decimal numbers
print(ceil(3.2))  #Gives the highest value of num ignoring the decimal.
print(sqrt(36))

#GETTING INPUT FROM USER:-

name = input("Enter your name: ")
age = input("Enter your age: ")
print("Hello " + name + "! You are "+ age+ " years old.")

#Basic Calculator:
x = input("Enter a number :")
y = input( "Enter a number :")
print(str(int(x) +  int(y)))

x = input("Enter a number :")
y = input( "Enter a number :")
z = float(x)+float(y)
print(z)

#MADLIB
place =input("Enter your favorite place: ")
color =input("Enter your favorite color: ")
food =input("Enter your favorite food: ")
print("I want to go to " + place)
print("My favorite color is "+ color)
print("I love to eat " + food)

#LISTS:Structure used to store multiple data values in square brackets.
friends = ["kevin","3.4","Bella","True","Theo","Kristen","Kim"]
        #     0      1      2       3   ==Indexing
print(friends)
print(friends[3])   #Can access elements based on their index
print(friends[-2] ) #Can access elements from the back of list using a - sign and starting form -1
print(friends[1:5]) #Can print selected elements from the list using : and range
print(friends[-2:])
print(friends[-6:])  #CHECKKKKKKKKKKK
friends[1]="John"
print(friends[1]) #Changing values
print(friends[-6:])

#LIST FUNCTIONS:
lucky_numbers = [4,3,15,17,23,42]
friends = ["Kevin","Bella","Theo","Kristen","Kim"]

#friends.extend(lucky_numbers) #Extend func allows a list to be appended by another list
#print(friends)
#friends.append("George") #allows to append an element in a list
friends.insert(1, "Kelly") #allows to insert an element by mentioning index position and the element.
friends.remove("Kim")
friends.pop() #pops out the last element in the list
#friends.clear() #clears the entire list
friends.sort()    #sorts the list in alphabetical order
print(friends)
lucky_numbers.sort()
lucky_numbers.reverse()
friends2 = friends.copy() #copies friends to friends2
print(friends2)
print(lucky_numbers)
#print(friends.index("Mike")) #Checks if a particular element is in the list

friends = ["kevin","3.4","Bella","True","Theo","Kristen","Kim"]
print(friends[-6:])