# -*- coding: utf-8 -*-
"""PythonPractice26Jan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Q2YeawWCY-62aHEXupvsGriEwptVXHkA
"""

#Tuples:Container used to store different values and is immutable i.e can't be changed or modified.
coordinates = (4,5)
coordinates =[ (4,5),(6,7),(5,9),(3,1),4] #List of tuples
#coordinates[1]=10
print(coordinates)

#Functions:collection of code which performs a specific task

def sayhi():
    print("Hello User")
  #  print("Google")
sayhi()

print("Top")
sayhi()
print("Bottom")

def say_hi(name,age):
    print("Hello "+ name +",You are " +age)
say_hi("Mike","34")
say_hi("Steve","12")

def say_hi(name,age):
    print("Hello "+ name +",You are " +str(age))
say_hi("Mike",34)
say_hi("Steve",12)  #1;34;16