# -*- coding: utf-8 -*-
"""Python_Basics_Rev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ojLUKqblcYsDR5QUjfdJtO1dDZOWr7K

Module is like a code library which can be used to borrow the code written by somebody else, is of 2 types:
Built-in modules are included in Python's standard library and do not require installation and can be used using import. Example: math, os etc.
External modules are not included in the standard library and need to be installed using a package manager like pip. Example: numpy, pandas etc.
"""

print("Hi I am \"Suzain\".")  #Escape Sequence

print("My name is \"Suzain\",\nI live in \"India\",\nI love \"Animals\".")

new_var = print("My name is \"Suzain\" " ," I live in \"India\"", sep="and")
new_var

print("Suzain", "24","Female", sep = "\n")  #Separator

'''new_var = print("My name is \"Suzain\" " ," I live in \"India\"", sep="and")
new_var'''                   ##Multi-line Comment
print("Hello")