# -*- coding: utf-8 -*-
"""python_basics_rev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ojLUKqblcYsDR5QUjfdJtO1dDZOWr7K

**Module** is like a code library which can be used to borrow the code written by somebody else, is of 2 types:

**Built-in** **modules** are included in Python's standard library and do not require installation and can be used using import. Example: math, os etc.

**External modules** are not included in the standard library and need to be installed using a package manager like pip. Example: numpy, pandas etc.
"""

print("Hi I am \"Suzain\".")  #Escape Sequence

print("My name is \"Suzain\",\nI live in \"India\",\nI love \"Animals\".")

new_var = print("My name is \"Suzain\" " ," I live in \"India\"", sep="and")
new_var

print("Suzain", "24","Female", sep = "\n")  #Separator

'''new_var = print("My name is \"Suzain\" " ," I live in \"India\"", sep="and")
new_var'''                   ##Multi-line Comment
print("Hello")

"""**Typecasting**: Conversion of one data type to another.
Has 2 types:  
**Implicit Typecasting:** Here, Python automatically converts one data type to another to avoid data loss or errors during operations.

**Explicit Typecasting:** It is when you manually convert one data type to another using functions like int(), float(), str(), etc.


"""

a = 1
b = 2
print(type(a))

a = "1"
b = "2"
print(type(a))
print(a + b)

a = int(2.2)
b = 2.2
print(type(a))

#Implicit Typecasting:
a = 2  #integer
b = 2.2  #float
print(a + b)  #float

#Explicit Typecasting:
a = "1"  #string
a = int(a)
print(type(a))

"""**Taking input from User using input() function:**"""

a = int(input("Enter the first number:"))
b = int(input("Enter the second number:"))
print("The sum of a and b is:",a+b)

name = input("Enter your name: ")
print("Hello ", name  + "! :)")

"""**Strings**: A string is a sequence of characters enclosed within single quotes (' '), double quotes (" "), or triple quotes (''' ''' or ''' ''').

*Immutable:* Once a string is created, its content cannot be changed.


*Ordered:* Strings maintain the order of characters, so indexing and slicing are possible.
"""

print("\"The Sun is awake so I am awake!\"\n\n", "\"Do you wanna build a Snowman?\"")

frozen = """Do you wanna build a snowman

Or ride our bikes around the halls?

I think some company is overdue, I've started talking to

The pictures on the walls

Hang in there, Joan

It gets a little lonely, all these empty rooms

Just watching the hours tick by

(tick, tock, tick, tock, tick, tock, tick, tock)

Elsa?

Please, I know you're in there

People are asking where you've been

\"They say have courage and I'm trying to

I'm right out here for you

Just let me in

We only have each other, it's just you and me\"

What are we gonna do?

\"Do you wanna build a snowman?\""""
print(frozen)

nm = """Harry"""
print(nm[-4:-2])
print(len(nm))

name = input("Enter your name:")
count = (len(name))
print("Your name has \"",count, "\" characters.")

char_count = name[0:5]
print(char_count)

char_count = name[:9]
print(char_count)

char_count = name[:] #By default takes values from 0 to len of string
print(char_count)

for i in name:
  print(name)

for i in name:
  print(i)

"""**String Methods:**

**The strip()** method in Python does not limit its operation to only the exact characters at the ends of the string.
Instead, it works by removing all occurrences of any character specified in its argument from the start and end of the string.
It does not remove characters from the middle of the string.
"""

a = "     London Paris      "
print(a)
print(a.strip())  #Removes whitespaces before and after the string.

"""The **rstrip() method** in Python is used to remove any trailing characters (characters at the end of a string).
By default, it removes whitespace (spaces, tabs, newlines) from the right side of the string
but you can also specify a set of characters to remove.
"""

str = name.rstrip("!")
print(str)

str = name.rstrip("")
print(str)

str_1 = "TheJungleBook@#$%**)(||\:;)"
print(str_1)

result = str_1.rstrip("Booklu@#$%*)(|\\:;")
print(result)

str = "TheJungleBook@#$%**)(||\:;)"
str_1= str.rstrip("@#$%**)(||\:;)")
print(str_1)

str_2 = str_1.upper()
print(str_2)

str_2 = str_1.lower()
print(str_2)

#Replace method replaces all occurences of a string with another string.

a = "My name is Paris.\nI live in Tokyo.\nI like to eat Turkey."
print(a)
print("******************************************")
x = a.replace("Paris", "Elf").replace("Turkey", "Pizza").replace(" ", " + ").replace(".","!").replace("\n","\n\n")
print(x)
#print(a.replace("Paris", "Elf").replace("Turkey", "Pizza").replace(" ", " + "))

a = "Yaaaay!\n" * 3
print(a)

"""**split():**

**The split()** method in Python is used to break a string into a list of substrings based on a specified delimiter.

By default, it splits the string at whitespace characters.
"""

a = "I love Persia"
b = a.split()
print(b)

a = "I-lovePersia"
b = a.split("-")
print(b)

# The maxsplit parameter in Python's split() method controls how many splits are performed on the string.
# After performing the specified number of splits, the rest of the string is returned as the final element of the resulting list.
a = "London Paris Vegas Rome Oslow Greece Italy"
b = a.split(" ", 2)                              #Performing maxsplit(2)
print(b)

"""**capitalize():**

The capitalize() method in Python is used to convert the first character of a string to uppercase and the rest of the characters to lowercase.

"""

str = "let's go!!!"
str_1 = str.capitalize()
print(str_1)

"""**center():**

The center() method in Python is used to center-align a string within a specified width.
It adds padding (spaces by default) on both sides of the string to ensure it is centered.
"""

str_2 = str_1.center(150,"|")
print(str_2)

"""**count():**

The count() method in Python is used to count the number of times a specific value appears in a string or a list.

It is available for both strings and lists.
"""

str = "bananaaa"
str_1 = str.count("a")
print(str_1)

text = "bananaaaanaaa"
print(len(text))
print(text.count("a"))
result = text.count("a", 1, 8)
print(result)

text = "banana is a fruit and banana is very good for health."
print(text.count("banana"))
print(text.count("is"))
print(text.count("apple"))

"""**endswith():**

The endswith() method  checks if a string ends with the specified suffix (character or substring).

It returns True if the string ends with the specified suffix; otherwise, it returns False.
"""

text = "Hello, welcome to my world."
result = text.endswith("world.")
print(result)

text = "Hello, welcome to my world."
result = text.endswith(".dd")
print(result)

string = "Python is fun to learn"
print(len(string))
print(string.endswith("is",0,9))
print(string.endswith("is",5,9))
print(string.endswith("is",0,11))

#You can provide a tuple of suffixes to check if the string ends with any one of them.
text = "Hello, welcome to my world."
result = text.endswith(("world.", "Python"))
print(result)

filename = input("Enter the file name: ")
if filename.endswith(".pdf"):
  print("This is a pdf file.")
else:
  print("This is not a pdf file.")

"""**find():**

The find() method is used to search for a specific substring in a string.

 It returns the lowest index of the substring if found; otherwise, it returns -1.


"""

string = "Python is fun to learn and I love to use Python language."
print(string.find("Python"))

string = "Python is fun to learn and I love to use Python language."
print(string.find("Python",6,56))

string = "Python is fun to learn and I love to use Python language."
print(string.find("Java"))    #find() returns -1 if the substring is not found.

