# -*- coding: utf-8 -*-
"""Reversing a string.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U2z6gy1mqGnEfGDbcUqDSUS_nET-C7_P
"""

#Program to get reverse of a string:
def reverse_string(x):
  a1=x[::-1]
  return a1
reverse_string("Suzain")