# -*- coding: utf-8 -*-
"""Revision_Session1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CdZU5xKxxHkJFEJfgmok1uEb8xxhXHHX
"""

print("Hello ","My name is Suzain")

print(type("hello"))

print(5)

print(type(5))

print("8")

print(type("8"))

'''Comments :Single line::: Use ctrl + / to comment or uncomment text
Inbuilt module
External Module:pip command'''
print("Hello my name is Suzain\n and I am a girl")

print("\"Hello\" my name is \"Suzain\"\n and I am a girl")

print("hey",6 ,7)

print("hey",6 ,7, sep ="&",end ="007\n") # sep separates values within a single print statement
print("Hellow ", end = "World\n")   # end is ued to append a value at the end of print statement
#Default sep:space

c = None
d = complex(2,5)
print(c)
print(d)
print("The type of c is:" , type(c))
print("The type of d is:" , type(d))

dic1 = {"Name":"Taylor" , "Age":"23", "Canvote": True }
print(dic1)

list_1 = ["apple","mango",True,[1.1 , 1.4],54]
 print(list_1)

tupp1 = ("parrot","crow",("Lion","Tiger"))
print(tupp1)

#Typecasting:conversion of one data type to another.
#Explicit:done by programmer and Implicit:done by python.
a = "12"
b = "3"
print(int(a)+int(b))

string = "15"
number = 7
string_number = int(string)
sum = number + string_number
print(sum)

a = 12
 b = 1.3
 sum = a+b
print(sum)
 print(type(a))
 print(type(b))
 print(type(sum))

a =int(input("Enter first number: "))
b =int(input("Enter second number: "))
result1 = a+b
print(result1)
result2 = a-b
print(result2)
result3 = a/b
print(result3)
result4 = a*b
print(result4)

print("He said,\"He wants to eat an apple.\"")

'''string_1 = Hello Mike
how are you?
I am good'''
print(string_1)

print('''hello      #comments
                   judy
      hops''')

name = "Harry"
print("Hello " + name[0:5])

print(name[2:])

names = "Harry,Taylor"
print(names[0:6])
print(len(names))
print(names[:6])
print(names[1:])
print(names[:])
print(names[0:len(names)-1])
print(names[2:len(names)-7])
print(names[0:-5])

nm = "Harry"
 print(len(nm))
 print(nm[-4:-2])

a = "Summer"    #Strings are immutable,operate on your string and generate a new copy
print(a.upper())

print(a.lower())

b = "   !zebra!!!!!!"
print(b.lstrip())
print(b.rstrip("!"))
print(b.replace("!zebra","Lion"))

c = "Zebra Giraffe Tiger Rhino"
print(c.split(" ")) #generates a list of these items

blog = "introDuctioN tO Js"
print(blog.capitalize())

print(blog.center(50))
print(len(blog))
print(len(blog.center(50)))

print(blog.count("i"))
print(blog.count("introDuctioN"))

