# -*- coding: utf-8 -*-
"""Revision_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nui8Wg5LwMYdNVR21RRw_upYprnUDpgM
"""

name = "Harry"
print("Hello" + name[0:10])

for character in name:
  print(character)

string_2 = '''Twinkle, twinkle,little star,
How I wonder what you are!
Up above the world so high,
Like a diamond in the sky.

Twinkle, twinkle, little star,
How I wonder what you are!'''
print(len(string_2))
for character in string_2:
  if (character == ','):
    print("Hii")
  else:
    print(character)

