# -*- coding: utf-8 -*-
"""Sets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TzQRq3XpFTne9BHo23xuHOZUYMg_xcTI
"""

#Set:is unordered collection of data items,stored in curly brackets separated by commas and do not contain repeated items.
s = {2,4,2,6}
print(s)
s1 = { "Mango","Banana","Apple","Mango"}
print(s1)
Suzain = set() #Creating empty set
print(type(Suzain))

#Accessing set items:
for value in s:
  print(value)