# -*- coding: utf-8 -*-
"""Short Hand if else.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fU6P2YGvKw6hGgcpjKCVNkwU2Ip5WPPq
"""

#Short Hand if else :
a =3
b = 300
print ("A") if a>b else print("=") if a = b else print ("B")

#Short Hand if else :
a = int(input("Enter a number,a: "))
b = int(input("Enter a number,b: "))
print (a) if a > b else print("Both Values are same") if a == b else print (b)

a = 3000
b = 409
print("A") if a>b else print("=") if a ==b else print("B")
c = 9 if a>b else 0
print(c)

a = int(input("Enter your age:"))
b =input("Enter your gender: ")
print("Right Credentials" )if a >= 18 and b == "M" else print("Not a valid candidate")