# -*- coding: utf-8 -*-
"""Time_complexity.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dGCBzyY5OJB6zSsMIMIAE1GY5p67ve08
"""

import numpy as np
import random

l = list(range(100))
random.shuffle(l)
l

q = 31
isFound = False
for ele in l:
  if ele == 31:
    print("Found")
    isFound = True
    break;
if isFound == False:
    print("Not Found")

