# -*- coding: utf-8 -*-
"""String Slicing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AL8MuhZn7TdIzskMr8pRMYaplwL4eESp
"""

#String Slicing:
names = "Suhana,Sadaf"
print(names[0:6])

fruit = "Mango"
mangoLen=len(fruit)
print("Mango is a ",  mangoLen, "letter word.")

print(fruit[0:4])
print(fruit[0:-2]) # 0 to len - 2
print(fruit[1:4])
print(fruit[:5]) #when not specified starts from 0 always
print(fruit[-1:-4]) #len - 1 to len - 4

country = "Norway"
for i in country:
  print(i)

nm = "Harry"
print(nm[-4:-2])