# -*- coding: utf-8 -*-
"""Swapping two numbers.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wkrjjfna9utddcSR1mEFP3pzloAkhxBn
"""

#Program to swap two numbers:
def swap(a,b):
  return b,a
a = int(input("Enter a number, a:"))
b = int(input("Enter a number, b:"))
a,b=swap(a,b)
print("After Swapping: ")
print("a = ",a)
print("b = ",b)